Patch Harfbuzz
We're getting an error on Ubuntu builds:

    pkg/harfbuzz/buffer.zig:292:18: error: root source file struct 'cimport' has no member named 'HB_BUFFER_CLUSTER_LEVEL_GRAPHEMES'
        graphemes = c.HB_BUFFER_CLUSTER_LEVEL_GRAPHEMES,
                    ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    .zig-cache/o/e54ea8e11cd4042106802b08d99b232a/cimport.zig:1:1: note: struct declared here
    pub const __builtin_bswap16 = @import("std").zig.c_builtins.__builtin_bswap16;
    ^~~

Appears to have been introduced to Ghostty here:
https://github.com/ghostty-org/ghostty/pull/10332

Based on the Harfbuzz change here, which has not yet made it into the
Ubuntu version:
https://github.com/harfbuzz/harfbuzz/pull/5069

`ClusterLevel.graphemes` is unused, at least currently. Just delete it
so the build works.